project_id = "zqskpspbyzptzjcoitwt"

[functions.cleanup-broken-images]
verify_jwt = true

[functions.subscription-payment]
verify_jwt = true

[functions.paystack-config]
verify_jwt = false

[functions.paystack-payment]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.notification-push-sender]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false